-The-Gossip-Project-master/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'users/show'
  get 'welcome/:first_name', to: 'static#welcome',as: 'welcome'
  get 'contact', to:'static#contact'
  get 'team', to:'static#team'
  get 'gossips/new/success', to: 'static#gossip_creation_success'
  resources :gossips
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

-The-Gossip-Project-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

-The-Gossip-Project-master/app/models/city.rb
class City < ApplicationRecord
    validates :name, presence: true
    has_many :users
end

-The-Gossip-Project-master/app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: {message: "Le titre doit être renseigné"}
    validates :title, length: { in: 3..14 }
    validates :content, presence: {message: "Saisissez le contenu de votre gossip!"} 
    
    belongs_to :user
    has_many :tags
end

-The-Gossip-Project-master/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender
    has_many :recipients
end

-The-Gossip-Project-master/app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips
end

-The-Gossip-Project-master/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :first_name, presence: true
    validates :last_name, presence: true   
    validates :email,
        presence: true, 
        uniqueness: {message: "Cet email est déjà utilisé"},
        format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
        
    has_many :gossips
    belongs_to :city, optional: true
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

-The-Gossip-Project-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

-The-Gossip-Project-master/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def index
        @gossips = Gossip.all
        puts "$!$!" *30
        puts Gossip.first.id
        puts "$!$!" *30
    end

    def create
        @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: User.all.sample.id)
        if @gossip.save
            redirect_to gossips_new_success_path 
        else
            render :new
        end
    end
    
    def new
        @gossip = Gossip.new
    end

    def show
        @gossips = Gossip.all
        @id = params[:id].to_i

        puts "$!$!" *30
        puts @id
        puts "$!$!" *30

        @first_name = User.find(@gossips[@id].user_id).first_name

        puts "$!$!" *30
        puts @first_name
        puts "$!$!" *30

        @last_name = User.find(@gossips[@id].user_id).last_name
        puts "$!$!" *30
        puts @last_name
        puts "$!$!" *30

        @user_id = User.find(@gossips[@id].user_id).id

        @title = @gossips[@id].title
        @content = @gossips[@id].content
    end

    def update
    end

end

-The-Gossip-Project-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end
end

-The-Gossip-Project-master/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
    @first_name = params[:first_name]
  end

  def contact
  end

  def team
  end
end

-The-Gossip-Project-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users = User.all
    @id = params[:id].to_i
    @user = @users[@id]
    @first_name = @user.first_name
    @last_name = @user.last_name
    @age = @user.age
    @email = @user.email
    @city = City.find(@user.city_id).name
  end

  def new
    @user = User.new
  end
  
  def create 
    puts params
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password])
    if @user.save
      redirect_to welcome_path(@user.first_name)
    else
      render :new
    end
  end

end

-The-Gossip-Project-master/app/helpers/application_helper.rb
module ApplicationHelper
end

-The-Gossip-Project-master/app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end

end

-The-Gossip-Project-master/app/helpers/users_helper.rb
module UsersHelper
end

-The-Gossip-Project-master/app/views/gossips/index.html.erb
<% @gossips.each do |gossip| %>
    <div style="width: 170rem; margin: auto;">
        <div class="card" style="width: 60%;">
          <div class="card-body">
            <h5 class="card-title"><a href= <%=gossip_path(gossip.id-1)%> > <%= gossip.title %></a></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= gossip.user.first_name %></h6>
            <p class="card-text"><%= gossip.content %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>

-The-Gossip-Project-master/app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) : </p>
    <ul>
        <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>


<%= form_tag(gossips_path, method: "post") do %>
    <%= label_tag("Nom") %>
    <%= text_field_tag(:first_name) %>

    <%= label_tag("Prenom") %>
    <%= text_field_tag(:last_name) %>

    <%= label_tag("Titre") %>
    <%= text_field_tag(:title) %>

    <%= text_area_tag(:content, "Ecrit ton gossip", size: "30x10") %>

    <%= submit_tag("Créer mon gossip") %>
<% end %>
  

-The-Gossip-Project-master/app/views/gossips/show.html.erb
<div class="card">
  <div class="card-header">
    <a href=<%=user_path(@user_id-1)%> ><%=@first_name%> <%=@last_name%></a>
  </div>
  <div class="card-body">
    <h4 class="card-title"> <%=@title %> </h4>
    <p class="card-text"> <%=@content%> </p>
    <a href="#" class="btn btn-primary">Editer le gossip</a>
  </div>
</div>

#<%=user_path(@first_name)%>

-The-Gossip-Project-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="nav-link" href="/welcome/username">Home</a>       
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
          <a class="nav-link" href="<%=team_path%>">Team</a> 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=contact_path%>">Contact</a> 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=new_user_path%>">Sign up</a> 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=contact_path%>">Log in</a> 
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

-The-Gossip-Project-master/app/views/users/new.html.erb
<% if @user.errors.any? %>
    <p>Erreurs : </p>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>


<%= form_tag(users_path, method: "post") do %>
<%= label_tag("Nom") %>
<%= text_field_tag(:first_name) %>

<%= label_tag("Prenom") %>
<%= text_field_tag(:last_name) %>

<%= label_tag("Email") %>
<%= text_field_tag(:email) %>

<%= label_tag("Password") %>
<%= text_field_tag(:password) %>

<%= submit_tag("Créer mon compte") %>
<% end %>

-The-Gossip-Project-master/app/views/users/show.html.erb
<h2> <%=@first_name%> <%=@last_name%> </h2>
<h2> Age : <%=@age%> </h2>
<h2> Email : <%=@email%> </h2>
<h2> Ville : <%=@city%> </h2>